name: wolt_state_management
version: "3.0.0"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^1.0.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
