name: wolt_di
description: This internal package provides a dependency injection mechanism 
  for demo apps.

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  # Flutter test tools
  flutter_test:
    sdk: flutter
