# coffee_maker_navigator_2/assets/pubspec.yaml
name: assets
description: >
  Holds the assets for the app. The assets are included in a
  separate package, to be able to share it with Widgetbook app.

version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

flutter:
  assets:
    - images/
