name: coffee_maker_navigator_2
description: The coffee maker example project to demonstrate the usage of wolt_modal_sheet library using Navigator 2.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  wolt_responsive_layout_grid: ^0.0.3
  wolt_di:
    path: ../../packages/wolt_di
  wolt_modal_sheet:
    path: ../..
  demo_ui_components:
    path: ../demo_ui_components
  assets:
    path: assets
  wolt_state_management:
    path: ../../packages/wolt_state_management

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
